name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
[[kv_namespaces]]
binding = "KV"
id = "7a7d4dc1674644878dd1745afe332999"

[[durable_objects.bindings]]
name = "SYNC_OBJECT"
class_name = "SyncObject"

[exports.SyncObject]
type = "durable-object"
storage = "sqlite"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
